[package]
name = "jango"
version = "0.2.4"
edition = "2024"
authors = ["Dalia Rojas Vallejo <dalia@rojasvallejo.com>"]
categories = ["command-line-utilities", "templates"]
keywords = ["cli", "app", "templates"]
license = "Unlicense"
readme = true
repository = "https://github.com/DavoReds/jango"
description = "A CLI program to populate your templates"

[dependencies]
camino = { version = "1.1.7", features = ["serde1"] }
clap = { version = "4.5.7", features = ["derive"] }
color-eyre = "0.6.3"
markdown = { version = "1.0.0-alpha.17", features = ["serde"] }
serde = "1.0.203"
tera = { version = "1.20.0", features = ["date-locale"] }
toml = { version = "0.8.14", default-features = false, features = ["parse"] }

[dev-dependencies]
proptest = "1.4.0"
rstest = { version = "0.21.0", default-features = false }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[profile.dist]
inherits = "release"
lto = "thin"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
unwrap_used = "deny"
