[package]
name = "jango"
version = "0.2.5"
edition = "2024"
authors = ["Dalia Rojas Vallejo <dalia@rojasvallejo.com>"]
categories = ["command-line-utilities", "templates"]
keywords = ["cli", "app", "templates"]
license = "Unlicense"
readme = true
repository = "https://github.com/DavoReds/jango"
description = "A CLI program to populate your templates"

[dependencies]
camino = { version = "1.2.5", features = ["serde1"] }
clap = { version = "4.6.6", features = ["derive"] }
color-eyre = "0.6.5"
markdown = { version = "1.0.0", features = ["serde"] }
serde = "1.0.229"
tera = "2.1.1"
toml = { version = "1.1.4", default-features = false, features = ["parse", "serde"] }

[dev-dependencies]
proptest = "1.11.0"
rstest = { version = "0.26.1", default-features = false }

[profile.release]
strip = true
opt-level = "z"
lto = "thin"
codegen-units = 1
panic = "abort"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
unwrap_used = "deny"
